[package]
name = "schnorr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.40"
sha3 = "0.10.1"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

